// Left menu
export const OPEN_LEFT_MENU = 'OPEN_LEFT_MENU';
export const CLOSE_LEFT_MENU = 'CLOSE_LEFT_MENU';
export const EXPAND_USERS_SUBMENU = 'EXPAND_USERS_SUBMENU';
export const COLLAPSE_USERS_SUBMENU = 'COLLAPSE_USERS_SUBMENU';
export const EXPAND_JUMPS_SUBMENU = 'EXPAND_JUMPS_SUBMENU';
export const COLLAPSE_JUMPS_SUBMENU = 'COLLAPSE_JUMPS_SUBMENU';

// Top menu
export const OPEN_TOP_MENU = 'OPEN_TOP_MENU';
export const CLOSE_TOP_MENU = 'CLOSE_TOP_MENU';



