export const FORGOT_PASSWORD_INITIAL_STATUS = 1;
export const FORGOT_PASSWORD_IN_PROCESS_STATUS = 2;
export const FORGOT_PASSWORD_ERROR_STATUS = 3;
export const FORGOT_PASSWORD_SUCCESS_STATUS = 4;

export const CHANGE_PASSWORD_INITIAL_STATUS = 1;
export const CHANGE_PASSWORD_IN_PROCESS_STATUS = 2;
export const CHANGE_PASSWORD_ERROR_STATUS = 3;
export const CHANGE_PASSWORD_SUCCESS_STATUS = 4;
