// Roles filtering
export const SET_MEMBER_ROLES_OPTIONS_FOR_FILTER = 'SET_MEMBER_ROLES_OPTIONS_FOR_FILTER';

// Status filtering
export const SET_MEMBER_STATUS_OPTIONS_FOR_FILTER = 'SET_MEMBER_STATUS_OPTIONS_FOR_FILTER';

// Set Members
export const SET_MEMBERS = 'SET_MEMBERS';



