// Roles filtering
export const SET_CLIENT_STATUS_OPTIONS_FOR_FILTER = 'SET_CLIENT_STATUS_OPTIONS_FOR_FILTER';

// Status filtering
export const SET_CLIENT_PAYMENT_STATUS_OPTIONS_FOR_FILTER = 'SET_CLIENT_PAYMENT_STATUS_OPTIONS_FOR_FILTER';

// Set Clients
export const SET_CLIENTS = 'SET_CLIENTS';



